### ISSUE TITLE
Implement pretty-printing for types and separate it from Type.toString

### ISSUE THREAD

**Issue by Blaisorblade** [inc-lc/ilc-scala#12]
As for terms and as we learned in PTS, we need both the default toString and pretty-printing as string representations for different use cases, instead of stretching a single representation for both needs.

In a perfect world, it would be cool to reuse some Scala port of a Haskell pretty-printing library (what we use is often inconvenient because it uses side effects, and lacks quite a few features). Last time I didn't find anything (but should look closer), not sure I'll be hacking that soon.

**Comment by Blaisorblade** [comment]
This is a dup of #10, but since I reference this issue elsewhere, I'm moving that description here.

**Comment by Toxaris** [comment]
> In a perfect world, it would be cool to reuse some Scala port of a Haskell pretty-printing library (what we use is often inconvenient because it uses side effects, and lacks quite a few features). Last time I didn't find anything (but should look closer), not sure I'll be hacking that soon.

Maybe that could be a topic for a BSc thesis?

**Comment by Blaisorblade** [comment]
>> In a perfect world, it would be cool to reuse some Scala port of a Haskell pretty-printing library (what we use is often inconvenient because it uses side effects, and lacks quite a few features). Last time I didn't find anything (but should look closer), not sure I'll be hacking that soon.

> Maybe that could be a topic for a BSc thesis?

That's probably a good idea (I was also thinking of that). A new search for `scala pretty printing` did turn up quite a few results, but maybe there's still something useful which would be good for some student to do. The main result is part of Kiama, but it seems it can be used without the rest of it, so it might be a good choice.

**Comment by yfcai** [comment]
Scala 2.10 came with a [pretty printing library][1] `scala.text`. It became deprecated in 2.11 to free up the name "text". I will investigate whether it's feasible to use this library, because teaching duty requires me to read it before next week anyway.

[1]: https://github.com/scala/scala/blob/v2.10.4/src/library/scala/text/Document.scala

**Comment by Toxaris** [comment]
If I understand the cryptic comments correctly, then maybe the documentation for Haskell's [Text.PrettyPrint.HughesPJ](hackage.haskell.org/package/pretty/docs/Text-PrettyPrint-HughesPJ.html) module might help.

**Comment by Blaisorblade** [comment]
> If I understand the cryptic comments in the Scala source correctly, then maybe the documentation for Haskell's Text.PrettyPrint.HughesPJ module might help.

Yeahish. My plan was to use some well-known Haskell design (like that one or the Leijen one).

[Kiama](https://code.google.com/p/kiama/wiki/PrettyPrinting)'s implementation seems to be a serious effort at a production library based on research [1].

> It became deprecated in 2.11 to free up the name "text".

IIRC, the idea was also that the library isn't that great — many combinators are missing and the library is [next to undocumented](http://www.scala-lang.org/api/current/index.html#scala.text.Document).

[1] ["Linear, bounded, functional pretty-printing"](http://journals.cambridge.org/abstract_S0956796808006990) by Swierstra and Chitil (Journal of Functional Programming, 19 (1), 2008)).

**Comment by yfcai** [comment]
Thanks.

**Comment by Toxaris** [comment]
Sorry for being not clear enough: I posted the link to the somewhat documented Haskell lib in order to address the well-known complaint about the Scala lib being next to undocumented.

**Comment by Toxaris** [comment]
I skimmed through the documentation for the Kiama pretty printing lib, and it makes lots of sense to me. Assuming the implementation is decent enough, I think we should use this.

**Comment by Blaisorblade** [comment]
Thanks for the comments @Toxaris! 

> Sorry for being not clear enough: I posted the link to the somewhat documented Haskell lib in order to address the well-known complaint about the Scala lib being next to undocumented.

Ah, I see, sorry! That Scala lib seemed also too minimal.

> Assuming the implementation is decent enough, I think we should use it \[the Kiama pretty printing library].

:+1:

**Comment by yfcai** [comment]
I agree with using Kiama. At the bottom of the doc there's a codeless paragraph about Parenthesisation of operators. We could use that. The paragraph says their algorithm comes from Norman Ramsey's [paper][1], which discusses unary and binary operators only. The link to the usage example Oberon0 leads to a stub wiki page.

[1]: http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-024X(1998100)28:12%3C1327::AID-SPE195%3E3.0.CO;2-C/abstract

**Comment by Toxaris** [comment]
The Oberon0 example is in Kiama's source distribution, here: https://code.google.com/p/kiama/source/browse/#hg%2Flibrary%2Fsrc%2Forg%2Fkiama%2Fexample%2Foberon0

**Comment by Blaisorblade** [comment]
I've looked at the code:

- [a pretty-printer for the easiest language variant](https://code.google.com/p/kiama/source/browse/library/src/org/kiama/example/oberon0/L0/source/SourcePrettyPrinter.scala), inheriting from
- [their base Oberon0 pretty-printer](https://code.google.com/p/kiama/source/browse/library/src/org/kiama/example/oberon0/base/source/SourcePrettyPrinter.scala), inheriting from
- [Kiama's ParenPrettyPrinter trait](https://code.google.com/p/kiama/source/browse/library/src/org/kiama/output/ParenPrettyPrinter.scala)

To paren-pretty-print expressions, the pretty-printing method overrides `ParenPrettyPrinter.toParenDoc`, and expressions should inherit from `PrettyExpression`. Operators should inherit from `PrettyBinaryExpression` or `PrettyUnaryExpression` and implement their methods to allow navigation. `toParenDoc` is, like in our code, a pattern match delegating to `super`.
We could have a (non-implicit, please) conversion from `Term` to `PrettyExpression`, to keep pretty-printing separate (though it's probably too much overhead in terms of boilerplate).

**Comment by yfcai** [comment]
> We could have a (non-implicit, please) conversion from Term to PrettyExpression, to keep pretty-printing separate (though it's probably too much overhead in terms of boilerplate).

Is there any reason to keep pretty-printing separate? If we want to pretty-print every term constructor, then the coupling between the two is tight, is it not?

**Comment by Blaisorblade** [comment]
> Is there any reason to keep pretty-printing separate? If we want to pretty-print every term constructor, then the coupling between the two is tight, is it not?

Separation of concerns would still suggest separating things, but this gets philosophical. But it might not be worth doing here.

**Comment by Toxaris** [comment]
> If we want to pretty-print every term constructor, then the coupling between the two is tight, is it not?

Note that coupling is directional.

- If the AST changes, pretty printing has to change. No good way to avoid that.
- But if the pretty printing changes, we might or might not have to change the AST, depending on the design.

**Comment by Blaisorblade** [comment]
> > Is there any reason to keep pretty-printing separate? If we want to pretty-print every term constructor, then the coupling between the two is tight, is it not?

> Separation of concerns would still suggest separating things, but this gets philosophical. But it might not be worth doing here.

If we keep pretty-printing separate, it's harder to do coverage checking (we can't with the current solution to the expression problem). So maybe we should let that go. But I'll leave that as future work.
I've already simplified #20 enough for merging to be plausible.
